# Generated by Django 3.1.5 on 2021-01-25 17:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import game.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('price', models.PositiveSmallIntegerField()),
                ('developer', models.CharField(max_length=55)),
                ('metascore', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('banner', models.ImageField(upload_to=game.helpers.upload_banner)),
                ('requirements_minimum', models.TextField(blank=True, null=True)),
                ('requirements_recommended', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ON_SALE', 'Satışta'), ('PRE_ORDER', 'Ön Sipariş'), ('SECOND_HAND', 'İkinci El'), ('SOLD', 'Satıldı')], default='ON_SALE', max_length=15)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=game.helpers.upload_media)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='game.game')),
            ],
        ),
    ]
