# Generated by Django 3.1.5 on 2021-01-22 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='game.Genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='languages',
            field=models.ManyToManyField(to='game.Language'),
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ManyToManyField(to='game.Platform'),
        ),
        migrations.AddField(
            model_name='game',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oyunlar', related_query_name='oyun', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameratings',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='game_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameratings',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='game_favourites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameratings',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='game_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
