# Generated by Django 3.1.5 on 2021-01-23 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameratings',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='game_total_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameratings',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='game_total_favourites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameratings',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='game_total_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameimage',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='game.game'),
        ),
        migrations.AddField(
            model_name='game',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='game.Genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='languages',
            field=models.ManyToManyField(to='game.Language'),
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ManyToManyField(to='game.Platform'),
        ),
        migrations.AddField(
            model_name='game',
            name='ratings',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_game', to='game.gameratings'),
        ),
        migrations.AddField(
            model_name='game',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', related_query_name='game_qs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_comments', to='game.game'),
        ),
    ]
