# Generated by Django 3.1.5 on 2021-01-19 23:37

from django.db import migrations, models
import game.models.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='banner',
            field=models.ImageField(upload_to=game.models.helpers.MediaDirectory.upload_media),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='image',
            field=models.ImageField(upload_to=game.models.helpers.MediaDirectory.upload_media),
        ),
    ]
