# Generated by Django 3.1.5 on 2021-01-20 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import game.models.upload_to


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_game_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameratings',
            old_name='wisheds',
            new_name='favorites',
        ),
        migrations.AlterField(
            model_name='game',
            name='banner',
            field=models.ImageField(upload_to=game.models.upload_to.MediaDirectory.upload_banner),
        ),
        migrations.AlterField(
            model_name='game',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oyunlar', related_query_name='oyun', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='image',
            field=models.ImageField(upload_to=game.models.upload_to.MediaDirectory.upload_media),
        ),
    ]
