# Generated by Django 3.1.5 on 2021-01-21 01:35

from django.conf import settings
from django.db import migrations, models
import game.models.upload_to


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_auto_20210121_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='banner',
            field=models.ImageField(upload_to=game.models.upload_to.MediaDirectory.upload_banner),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='image',
            field=models.ImageField(upload_to=game.models.upload_to.MediaDirectory.upload_media),
        ),
    ]
