# Generated by Django 3.1.5 on 2021-01-20 05:04

import builtins
from django.db import migrations, models
import game.models.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210120_0237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default=builtins.id, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='banner',
            field=models.ImageField(upload_to=game.models.helpers.MediaDirectory.upload_banner),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='image',
            field=models.ImageField(upload_to=game.models.helpers.MediaDirectory.upload_media),
        ),
        migrations.AlterField(
            model_name='gameratings',
            name='comments',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='gameratings',
            name='likes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='gameratings',
            name='wisheds',
            field=models.JSONField(default=dict),
        ),
    ]
