# Generated by Django 3.1.5 on 2021-01-18 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gameratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameratings',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='game.game'),
        ),
    ]
