# Generated by Django 3.1.5 on 2021-01-23 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_metascore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='likes',
        ),
    ]
