# Generated by Django 3.1.5 on 2021-01-18 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210119_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameratings',
            name='id',
        ),
        migrations.AlterField(
            model_name='gameratings',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ratings', serialize=False, to='game.game'),
        ),
    ]
