# Generated by Django 3.1.5 on 2021-01-20 05:14

from django.db import migrations, models
import game.models.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210120_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='banner',
            field=models.ImageField(upload_to=game.models.helpers.MediaDirectory.upload_banner),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='image',
            field=models.ImageField(upload_to=game.models.helpers.MediaDirectory.upload_media),
        ),
    ]
