# Generated by Django 3.1.5 on 2021-01-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_game_likes'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='game',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('ON_SALE', 'Satışta'), ('PRE_ORDER', 'Ön Sipariş'), ('SECOND_HAND', 'İkinci El'), ('SOLD', 'Satıldı')], default='ON_SALE', max_length=15),
        ),
    ]
