# Generated by Django 3.1.5 on 2021-01-25 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210125_2022'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', related_query_name='checkout', to=settings.AUTH_USER_MODEL)),
                ('reference', models.ManyToManyField(related_name='checkouts', related_query_name='checkout', to='game.Game')),
            ],
        ),
    ]
