# Generated by Django 3.1.5 on 2021-01-23 23:07

from django.db import migrations, models
import user.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(default='default-profile-pic.jpg', upload_to=user.helpers.upload_media),
        ),
    ]
