# Generated by Django 3.1.5 on 2021-01-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20210121_0856'),
        ('user', '0003_delete_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='item',
        ),
        migrations.AddField(
            model_name='checkout',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='checkout_item', to='game.Game'),
        ),
    ]
