# Generated by Django 3.1.5 on 2021-01-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210125_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
