# Generated by Django 3.1.4 on 2021-01-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('price', models.PositiveSmallIntegerField()),
                ('developer', models.CharField(max_length=55)),
                ('description', models.TextField()),
                ('requirements_minimum', models.TextField()),
                ('requirements_recommended', models.TextField()),
                ('genres', models.ManyToManyField(to='game.Genres')),
                ('languages', models.ManyToManyField(to='game.Languages')),
                ('platform', models.ManyToManyField(to='game.Platform')),
            ],
        ),
    ]
