# Generated by Django 3.1.4 on 2021-01-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
        migrations.RenameModel(
            old_name='Languages',
            new_name='Language',
        ),
    ]
