# Generated by Django 3.1.4 on 2021-01-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210117_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='on_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='pre_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
