# Generated by Django 3.1.5 on 2021-01-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210117_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Oyun', 'verbose_name_plural': 'Oyunlar'},
        ),
        migrations.AddField(
            model_name='game',
            name='stock',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
